services:
  postgres:
    image: postgres:16.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "V3ry$3cr3t"
      POSTGRES_USER: "shoppingcart"
      POSTGRES_DB: "shoppingcart"
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db:
